// Code generated by "stringer -type=PerfdataIdentifier"; DO NOT EDIT

package gonag

import "fmt"

const _PerfdataIdentifier_name = "WarnCritMinMax"

var _PerfdataIdentifier_index = [...]uint8{0, 4, 8, 11, 14}

func (i PerfdataIdentifier) String() string {
	if i < 0 || i >= PerfdataIdentifier(len(_PerfdataIdentifier_index)-1) {
		return fmt.Sprintf("PerfdataIdentifier(%d)", i)
	}
	return _PerfdataIdentifier_name[_PerfdataIdentifier_index[i]:_PerfdataIdentifier_index[i+1]]
}
