// Code generated by "stringer -type=PerfdataThresholdIdentifier"; DO NOT EDIT

package gonag

import "fmt"

const _PerfdataThresholdIdentifier_name = "WarnCritMinMax"

var _PerfdataThresholdIdentifier_index = [...]uint8{0, 4, 8, 11, 14}

func (i PerfdataThresholdIdentifier) String() string {
	if i < 0 || i >= PerfdataThresholdIdentifier(len(_PerfdataThresholdIdentifier_index)-1) {
		return fmt.Sprintf("PerfdataThresholdIdentifier(%d)", i)
	}
	return _PerfdataThresholdIdentifier_name[_PerfdataThresholdIdentifier_index[i]:_PerfdataThresholdIdentifier_index[i+1]]
}
