// Code generated by "stringer -type=ReturnCode"; DO NOT EDIT

package gonag

import "fmt"

const _ReturnCode_name = "OKWARNINGCRITICALUNKNOWN"

var _ReturnCode_index = [...]uint8{0, 2, 9, 17, 24}

func (i ReturnCode) String() string {
	if i < 0 || i >= ReturnCode(len(_ReturnCode_index)-1) {
		return fmt.Sprintf("ReturnCode(%d)", i)
	}
	return _ReturnCode_name[_ReturnCode_index[i]:_ReturnCode_index[i+1]]
}
